app = "anirank"
primary_region = "qro"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/api/health"

[env]
APP_PORT = "8080"
PORT = "8080"
