package rbac

import (
	"sort"
	"testing"
)

// TestBuildPermissionRegistry_GeneratesAllExpectedSlugs verifies that all permission
// slugs currently used in router.go are generated by the registry.
func TestBuildPermissionRegistry_GeneratesAllExpectedSlugs(t *testing.T) {
	perms := BuildPermissionRegistry()
	slugSet := make(map[string]bool, len(perms))
	for _, p := range perms {
		slugSet[p.Slug] = true
	}

	// These are extracted from HasPermissionMiddleware calls in router.go
	expectedSlugs := []string{
		// CRUD entities
		"anime.create", "anime.edit", "anime.delete",
		"song.create", "song.edit", "song.delete",
		"artist.create", "artist.edit", "artist.delete",
		// Taxonomies
		"taxonomy.years.create", "taxonomy.years.edit", "taxonomy.years.delete",
		"taxonomy.seasons.create", "taxonomy.seasons.edit", "taxonomy.seasons.delete",
		"taxonomy.formats.create", "taxonomy.formats.edit", "taxonomy.formats.delete",
		"taxonomy.genres.create", "taxonomy.genres.edit", "taxonomy.genres.delete",
		"taxonomy.studios.create", "taxonomy.studios.edit", "taxonomy.studios.delete",
		"taxonomy.producers.create", "taxonomy.producers.edit", "taxonomy.producers.delete",
		// Manage
		"reports.manage", "users.manage", "permissions.manage",
		"tournament.manage", "announcement.manage", "badge.manage",
		"webhooks.manage", "partners.manage",
	}

	for _, slug := range expectedSlugs {
		if !slugSet[slug] {
			t.Errorf("Expected permission slug %q not generated by registry", slug)
		}
	}
}

// TestBuildPermissionRegistry_NoDuplicateSlugs ensures no duplicate slugs are generated.
func TestBuildPermissionRegistry_NoDuplicateSlugs(t *testing.T) {
	perms := BuildPermissionRegistry()
	seen := make(map[string]bool, len(perms))

	for _, p := range perms {
		if seen[p.Slug] {
			t.Errorf("Duplicate permission slug: %q", p.Slug)
		}
		seen[p.Slug] = true
	}
}

// TestBuildPermissionRegistry_AllFieldsPopulated ensures every permission has a non-empty Name, Slug, and Description.
func TestBuildPermissionRegistry_AllFieldsPopulated(t *testing.T) {
	perms := BuildPermissionRegistry()

	for _, p := range perms {
		if p.Name == "" {
			t.Errorf("Permission with slug %q has empty Name", p.Slug)
		}
		if p.Slug == "" {
			t.Error("Permission has empty Slug")
		}
		if p.Description == "" {
			t.Errorf("Permission with slug %q has empty Description", p.Slug)
		}
	}
}

// TestBuildRoleMatrix_AdminHasAllPermissions verifies the admin role receives every permission.
func TestBuildRoleMatrix_AdminHasAllPermissions(t *testing.T) {
	perms := BuildPermissionRegistry()
	matrix := BuildRoleMatrix(perms)

	adminPerms := matrix["admin"]
	if len(adminPerms) != len(perms) {
		t.Errorf("Admin should have %d permissions, got %d", len(perms), len(adminPerms))
	}

	// Verify every generated perm is in admin's list
	adminSet := make(map[string]bool, len(adminPerms))
	for _, s := range adminPerms {
		adminSet[s] = true
	}
	for _, p := range perms {
		if !adminSet[p.Slug] {
			t.Errorf("Admin missing permission: %q", p.Slug)
		}
	}
}

// TestBuildRoleMatrix_EditorHasNoDeleteOrRestrictedManage verifies editor restrictions.
func TestBuildRoleMatrix_EditorHasNoDeleteOrRestrictedManage(t *testing.T) {
	perms := BuildPermissionRegistry()
	matrix := BuildRoleMatrix(perms)

	editorPerms := make(map[string]bool)
	for _, s := range matrix["editor"] {
		editorPerms[s] = true
	}

	// Editor must NOT have delete permissions
	forbiddenSuffixes := []string{".delete"}
	for slug := range editorPerms {
		for _, suffix := range forbiddenSuffixes {
			if len(slug) > len(suffix) && slug[len(slug)-len(suffix):] == suffix {
				t.Errorf("Editor should NOT have delete permission: %q", slug)
			}
		}
	}

	// Editor must NOT have these manage permissions
	forbiddenManage := []string{
		"users.manage", "permissions.manage", "badge.manage",
		"announcement.manage", "webhooks.manage", "partners.manage",
	}
	for _, slug := range forbiddenManage {
		if editorPerms[slug] {
			t.Errorf("Editor should NOT have permission: %q", slug)
		}
	}

	// Editor MUST have these manage permissions
	requiredManage := []string{"reports.manage", "tournament.manage"}
	for _, slug := range requiredManage {
		if !editorPerms[slug] {
			t.Errorf("Editor missing required permission: %q", slug)
		}
	}
}

// TestBuildRoleMatrix_CreatorHasOnlyCreatePermissions verifies creator gets only *.create.
func TestBuildRoleMatrix_CreatorHasOnlyCreatePermissions(t *testing.T) {
	perms := BuildPermissionRegistry()
	matrix := BuildRoleMatrix(perms)

	creatorPerms := matrix["creator"]

	for _, slug := range creatorPerms {
		if !isEntityAction(slug, "create") {
			t.Errorf("Creator has non-create permission: %q", slug)
		}
	}

	// Verify all create permissions are included
	allCreateSlugs := []string{}
	for _, p := range perms {
		if isEntityAction(p.Slug, "create") {
			allCreateSlugs = append(allCreateSlugs, p.Slug)
		}
	}

	if len(creatorPerms) != len(allCreateSlugs) {
		t.Errorf("Creator should have %d create permissions, got %d", len(allCreateSlugs), len(creatorPerms))
	}
}

// TestBuildRoleMatrix_OwnerNotInMatrix verifies owner is excluded from the matrix.
func TestBuildRoleMatrix_OwnerNotInMatrix(t *testing.T) {
	perms := BuildPermissionRegistry()
	matrix := BuildRoleMatrix(perms)

	if _, exists := matrix["owner"]; exists {
		t.Error("Owner should NOT be in the role matrix (has middleware bypass)")
	}
}

// TestAddingNewEntity_AutomaticallyGeneratesPermissions simulates adding a new entity.
func TestAddingNewEntity_AutomaticallyGeneratesPermissions(t *testing.T) {
	// Save original and restore after test
	original := CRUDEntities
	defer func() { CRUDEntities = original }()

	// Add a hypothetical new entity
	CRUDEntities = append(CRUDEntities, "playlist")

	perms := BuildPermissionRegistry()
	slugSet := make(map[string]bool, len(perms))
	for _, p := range perms {
		slugSet[p.Slug] = true
	}

	expectedNew := []string{"playlist.create", "playlist.edit", "playlist.delete"}
	for _, slug := range expectedNew {
		if !slugSet[slug] {
			t.Errorf("New entity permission %q not auto-generated", slug)
		}
	}

	// Verify role matrix auto-assigns new entity
	matrix := BuildRoleMatrix(perms)

	adminSet := make(map[string]bool)
	for _, s := range matrix["admin"] {
		adminSet[s] = true
	}
	for _, slug := range expectedNew {
		if !adminSet[slug] {
			t.Errorf("Admin should auto-receive new permission: %q", slug)
		}
	}

	editorSet := make(map[string]bool)
	for _, s := range matrix["editor"] {
		editorSet[s] = true
	}
	if !editorSet["playlist.create"] {
		t.Error("Editor should auto-receive playlist.create")
	}
	if !editorSet["playlist.edit"] {
		t.Error("Editor should auto-receive playlist.edit")
	}
	if editorSet["playlist.delete"] {
		t.Error("Editor should NOT auto-receive playlist.delete")
	}

	creatorSet := make(map[string]bool)
	for _, s := range matrix["creator"] {
		creatorSet[s] = true
	}
	if !creatorSet["playlist.create"] {
		t.Error("Creator should auto-receive playlist.create")
	}
	if creatorSet["playlist.edit"] {
		t.Error("Creator should NOT auto-receive playlist.edit")
	}
}

// TestPermissionCount ensures the total count matches expectations.
func TestPermissionCount(t *testing.T) {
	perms := BuildPermissionRegistry()

	expectedCRUD := len(CRUDEntities) * len(CRUDActions)          // 3 entities × 3 actions = 9
	expectedTax := len(TaxonomyEntities) * len(CRUDActions)        // 6 taxonomies × 3 actions = 18
	expectedManage := len(ManagePermissions)                       // 8
	expectedTotal := expectedCRUD + expectedTax + expectedManage   // 35

	if len(perms) != expectedTotal {
		t.Errorf("Expected %d total permissions (CRUD:%d + Tax:%d + Manage:%d), got %d",
			expectedTotal, expectedCRUD, expectedTax, expectedManage, len(perms))
	}
}

// TestRoleMatrixPermissionCounts validates exact counts per role.
func TestRoleMatrixPermissionCounts(t *testing.T) {
	perms := BuildPermissionRegistry()
	matrix := BuildRoleMatrix(perms)

	// Admin: all permissions
	if len(matrix["admin"]) != len(perms) {
		t.Errorf("Admin: expected %d permissions, got %d", len(perms), len(matrix["admin"]))
	}

	// Editor: create + edit (no delete) from CRUD + taxonomy, plus reports.manage + tournament.manage
	expectedEditorCRUD := len(CRUDEntities) * 2       // 3 × 2 = 6
	expectedEditorTax := len(TaxonomyEntities) * 2     // 6 × 2 = 12
	expectedEditorManage := 2                          // reports.manage, tournament.manage
	expectedEditor := expectedEditorCRUD + expectedEditorTax + expectedEditorManage

	if len(matrix["editor"]) != expectedEditor {
		t.Errorf("Editor: expected %d permissions, got %d", expectedEditor, len(matrix["editor"]))

		// Print what editor has for debugging
		sort.Strings(matrix["editor"])
		t.Logf("Editor permissions: %v", matrix["editor"])
	}

	// Creator: only create permissions from CRUD + taxonomy
	expectedCreator := len(CRUDEntities) + len(TaxonomyEntities) // 3 + 6 = 9
	if len(matrix["creator"]) != expectedCreator {
		t.Errorf("Creator: expected %d permissions, got %d", expectedCreator, len(matrix["creator"]))
	}
}
