CREATE TABLE IF NOT EXISTS artists (
    id BIGSERIAL PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    name_jp VARCHAR(255),
    slug VARCHAR(255) UNIQUE NOT NULL,
    status BOOLEAN DEFAULT FALSE,
    favorites_count INTEGER DEFAULT 0,
    enabled_songs INTEGER DEFAULT 0,
    disabled_songs INTEGER DEFAULT 0,
    anilist_id BIGINT UNIQUE NULL,
    animethemes_id VARCHAR(255) UNIQUE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
