CREATE TABLE IF NOT EXISTS animes (
    id BIGSERIAL PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    anilist_id BIGINT UNIQUE NULL,
    status BOOLEAN DEFAULT FALSE,
    songs_count INTEGER DEFAULT 0,
    year_id BIGINT NULL REFERENCES years(id) ON DELETE SET NULL,
    season_id BIGINT NULL REFERENCES seasons(id) ON DELETE SET NULL,
    format_id BIGINT NULL REFERENCES formats(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS animes_status_idx ON animes (status);
